ALTER TABLE IF EXISTS "entries" DROP CONSTRAINT IF EXISTS "entries_owner_fkey";
ALTER TABLE IF EXISTS "contact" DROP CONSTRAINT IF EXISTS "contact_owner_fkey";
ALTER TABLE IF EXISTS "tag" DROP CONSTRAINT IF EXISTS "tag_entries_fkey";

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "entries";
DROP TABLE IF EXISTS "tag";
DROP TABLE IF EXISTS "contact";