version: '3.9'
services:
  db:
    container_name: blog-backend
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'