### Variable 
@host=http://localhost:8080/api/v1

###
POST {{host}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "teguh",
    "full_name": "Teguh Atma Yudha",
    "email": "teguh@email.com",
    "password": "adminadmin"
}

### 

GET {{host}}/users/teguh HTTP/1.1
