// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"database/sql"
	"time"
)

type Contact struct {
	ID        int64          `json:"id"`
	Owner     string         `json:"owner"`
	Github    sql.NullString `json:"github"`
	Twitter   sql.NullString `json:"twitter"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	TagName   string    `json:"tag_name"`
	Blog      string    `json:"blog"`
	Title     string    `json:"title"`
	ReadTime  string    `json:"read_time"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             sql.NullInt64 `json:"id"`
	Username       string        `json:"username"`
	HashedPassword string        `json:"hashed_password"`
	FullName       string        `json:"full_name"`
	Email          string        `json:"email"`
	UpdatedAt      time.Time     `json:"updated_at"`
	CreatedAt      time.Time     `json:"created_at"`
}
