// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteContact(ctx context.Context, id int64) error
	DeleteEntries(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	GetEntries(ctx context.Context, id int64) (Entry, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListContact(ctx context.Context, arg ListContactParams) ([]Contact, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTag(ctx context.Context, arg ListTagParams) ([]Tag, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateEntries(ctx context.Context, arg UpdateEntriesParams) (Entry, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
